### ISSUE TITLE
Pause menu gomb nem  működik

### ISSUE THREAD

**Issue by SzMarci77** [Dumach/mosze-2024-szen-dioxiddal-dusitott#23]
csak a 4-es és az 5-ös pályán nem jó

**Comment by SzMarci77** [comment]
+ a 3. pályán nincs progress bar

**Comment by Dumach** [comment]
Leghamarabb este 6-kor meg tudom csinalni

**Comment by Dumach** [comment]
Kész van, a gombok OnClick eseményét kellett újra fel programoznom
